# HMM Algorithm

In [11]:
import numpy as np

## (A) the Viterbi_HMM function

In [12]:
def Viterbi_HMM(pi_init, A, B, O):
    T = len(O) # length of the output scequence
    N = A.shape[0] # number of states
    O -= 1
    
#     S = np.zeros((N, T)) # one step per column
#     W = np.zeros((N, T)) # one step per column
    S = np.full((N, T), -1, dtype=float) # one step per column
    W = np.full((N, T), -1, dtype=float) # one step per column
    
    # return values
    P = 0
    Q = np.zeros(T, dtype=int)
    
    # initialization
    print('INITIALIZATION')
    for j in range(N):
        S[j, 0] = pi_init[j, 0] * B[O[0], j]
        W[j, 0] = 0
    print('After initialize, S =\n', S)
    
    # recursion
    print('RECURSION')
    for t in range(1, T):
        for j in range(N):
            tmp_max = -1
            for i in range(N):
                tmp = S[i, t-1] * A[i, j] * B[O[t], j]
                if tmp > S[j, t]:
                    S[j, t] = tmp
            
                tmp = S[i, t-1] * A[i, j]
                if tmp > tmp_max:
                    tmp_max = tmp
                    W[j, t] = i
        print('after t =', t, ':')
        print('S =\n', S)
        print('W =\n', W)
        print('-------------------------')
        
    # termination
    print('TERMINATION')
    for j in range(N):
        tmp = S[j, T-1]
        if tmp > P:
            P = tmp
            Q[T-1] = j
            
    # backtracking
    print('BACKTRACK')
    for t in range(T-2, -1, -1): # loop from T-2 to 0
        Q[t] = W[Q[t+1], t+1]
        
    Q += 1
    return P, Q

## (B) - (1): Model the problem as a HMM

In [13]:
pi_init = np.array([[1], [0]])
A = np.array([[0.4, 0.6], [0.4, 0.6]])
B = np.array([[0.6, 0.4], [0.4, 0.6]])
O1 = np.array([1, 2, 2, 2, 1], dtype=int)
O2 = np.array([2, 2, 2, 1, 1, 1, 1], dtype=int)

## (B) - (2): Use the function in (A) to find the best state sequence and repective path probability

#### For the observation sequence : {H, T, T, T, H}

In [14]:
P, Q = Viterbi_HMM(pi_init, A, B, O1)
print('\nThe best state sequence and repective path probability:', Q, P)

INITIALIZATION
After initialize, S =
 [[ 0.6 -1.  -1.  -1.  -1. ]
 [ 0.  -1.  -1.  -1.  -1. ]]
RECURSION
after t = 1 :
S =
 [[ 0.6    0.096 -1.    -1.    -1.   ]
 [ 0.     0.216 -1.    -1.    -1.   ]]
W =
 [[ 0.  0. -1. -1. -1.]
 [ 0.  0. -1. -1. -1.]]
-------------------------
after t = 2 :
S =
 [[ 0.6      0.096    0.03456 -1.      -1.     ]
 [ 0.       0.216    0.07776 -1.      -1.     ]]
W =
 [[ 0.  0.  1. -1. -1.]
 [ 0.  0.  1. -1. -1.]]
-------------------------
after t = 3 :
S =
 [[ 0.6        0.096      0.03456    0.0124416 -1.       ]
 [ 0.         0.216      0.07776    0.0279936 -1.       ]]
W =
 [[ 0.  0.  1.  1. -1.]
 [ 0.  0.  1.  1. -1.]]
-------------------------
after t = 4 :
S =
 [[0.6        0.096      0.03456    0.0124416  0.00671846]
 [0.         0.216      0.07776    0.0279936  0.00671846]]
W =
 [[0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1.]]
-------------------------
TERMINATION
BACKTRACK

The best state sequence and repective path probability: [1 2 2 2 1] 0.0067184639999999

#### For the observation sequence : {T, T, T, H, H, H, H}

In [15]:
P, Q = Viterbi_HMM(pi_init, A, B, O2)
print('\nThe best state sequence and repective path probability:', Q, P)

INITIALIZATION
After initialize, S =
 [[ 0.4 -1.  -1.  -1.  -1.  -1.  -1. ]
 [ 0.  -1.  -1.  -1.  -1.  -1.  -1. ]]
RECURSION
after t = 1 :
S =
 [[ 0.4    0.064 -1.    -1.    -1.    -1.    -1.   ]
 [ 0.     0.144 -1.    -1.    -1.    -1.    -1.   ]]
W =
 [[ 0.  0. -1. -1. -1. -1. -1.]
 [ 0.  0. -1. -1. -1. -1. -1.]]
-------------------------
after t = 2 :
S =
 [[ 0.4      0.064    0.02304 -1.      -1.      -1.      -1.     ]
 [ 0.       0.144    0.05184 -1.      -1.      -1.      -1.     ]]
W =
 [[ 0.  0.  1. -1. -1. -1. -1.]
 [ 0.  0.  1. -1. -1. -1. -1.]]
-------------------------
after t = 3 :
S =
 [[ 0.4        0.064      0.02304    0.0124416 -1.        -1.
  -1.       ]
 [ 0.         0.144      0.05184    0.0124416 -1.        -1.
  -1.       ]]
W =
 [[ 0.  0.  1.  1. -1. -1. -1.]
 [ 0.  0.  1.  1. -1. -1. -1.]]
-------------------------
after t = 4 :
S =
 [[ 0.4         0.064       0.02304     0.0124416   0.00298598 -1.
  -1.        ]
 [ 0.          0.144       0.05184     0.012441